name: 'Ray Harmon '
favicon: null
layout_spectrum: 0.5899871767032892
typography_spectrum: 0.16606066771782935
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.4195080641657114
  lightness: 0.012536586495116353
  saturation: 0.8222492993809283
  rhythmicContrast: 0.8162550197448581
purpose: []
