name: 'Ray Harmon '
favicon: null
layout_spectrum: 0
typography_spectrum: 0.24732
title: 'The short film "Ray Harmon"'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#8b98a0'
    - '#bcc6c7'
    - '#1b1209'
    - '#6a593f'
    - '#f16f81'
  brandStrength: 0
  lightness: 0.012536586495116353
  saturation: 0
  rhythmicContrast: 0.25
purpose: []
